---

- hosts: VA1T3NCOPS-D01 
  tasks:
  - name: Stop chatops.service
    raw: /usr/bin/systemctl stop chatops.service

- hosts: ChatOpsGlobal
  tasks:
  - name: Stop chatops.service
    raw: /usr/bin/systemctl stop chatops.service

- hosts: ChatOpsSatellite
  tasks:
  - name: Stop chatops.service
    raw: /usr/bin/systemctl stop chatops.service
