---

- hosts: ChatOpsDevelopment
  tasks:
  - name: Delete the /etc/resolv.conf
    raw: /usr/bin/rm -rf /etc/resolv.conf
  - name: Create and configure the new /etc/resolv.conf
    template:
      src=templates/MGMT_resolv.conf
      dest=/etc/resolv.conf
      owner=root
      group=root
      mode=0644


- hosts: ChatOpsDevelopment 
  tasks:
  - name: Stop chatops.service
    raw: /usr/bin/systemctl stop chatops.service
  - name: Disable chatops.service
    raw: /usr/bin/systemctl disable chatops.service
  - name: Delete the current symbolic link chatops.service in /etc/systemd/system/
    raw: /usr/bin/rm -f /etc/systemd/system/chatops.service
  - name: Delete the current file chatops.service in /opt/chatops/
    raw: /usr/bin/rm -f /opt/chatops/chatops.service
  - name: Delete the current file hubot-clc-diags.js in /opt/chatops/scripts
    raw: /usr/bin/rm -f /opt/chatops/scripts/hubot-clc-diags.js
  - name: Fill in the variables and copy templates/chatops.service to remote /etc/systemd/system/chatops.service
    template:
      src=templates/chatops.service
      dest=/etc/systemd/system/chatops.service
      owner=root
      group=root
      mode=0755
  - name: Copy the updated files/CC_ChatOps_Development/external-scripts.json to /opt/chatops/external-scripts.json
    copy:
      src=files/CC_ChatOps_Development/external-scripts.json
      dest=/opt/chatops/external-scripts.json
      owner=chatops
      group=chatops
      mode=0644
  - name: Copy the updated files/CC_ChatOps_Development/scripts/hubot-clc-diags.js to /opt/chatops/scripts/hubot-clc-diags.js
    copy:
      src=files/CC_ChatOps_Development/scripts/hubot-clc-diags.js
      dest=/opt/chatops/scripts/hubot-clc-diags.js
      owner=chatops
      group=chatops
      mode=0755
  - name: Create symbolic /opt/chatops/chatops.service to /etc/systemd/system/chatops.service
    raw: ln -s /etc/systemd/system/chatops.service /opt/chatops/chatops.service
  - name: Register and enable the chatops.service
    service: name=chatops.service pattern=/etc/systemd/system/chatops.service enabled=yes
  - name: Reload systemctl
    raw: /usr/bin/systemctl daemon-reload
  - name: Install the latest version of jwhois
    yum: name=jwhois state=latest
  - name: Install the latest version of geoip
    yum: name=geoip state=latest
  - name: Start the chatops.service
    service: name=chatops.service state=started


- hosts: ChatOpsDevelopment
  tasks:
  - name: Clean restart chatops.service
    raw: /usr/bin/systemctl restart chatops.service

