---

################################################################################
#  description: Uninstalls Skynet Minion on RHEL7x
#  usage: ansible-playbook ChatOps_SKYMINION-GLOBAL_Uninstall-playbook.yml --extra-vars 'HostOrGroup=YourServerOrGroupNameGoesHere'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Uninstall Skynet Minion on RHEL7x
  hosts: "{{ HostOrGroup|default ('FATAL ERROR --> HostOrGroup NOT SET! You must specify either a Host or a Group name!') }}"
  serial: "100%"
  gather_facts: False
  tasks:


# service - Manage services
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Stop and disable the skyminion.service service
    service:
      name: skyminion.service
      enabled: no
      state: stopped


# file - Sets attributes of files and folders
# REF: http://docs.ansible.com/ansible/file_module.html
#######################################################

# /opt/skyminion
  - name: Delete PROD directory /opt/skyminion
    file:
      path: /opt/skyminion
      state: absent

# /etc/systemd/system/skyminion.service
  - name: Delete service file /etc/systemd/system/skyminion.service
    file:
      path: /etc/systemd/system/skyminion.service
      state: absent


# raw - Executes a low-down and dirty SSH command
# REF: http://docs.ansible.com/ansible/raw_module.html
######################################################

  - name: systemctl daemon-reload
    shell: systemctl daemon-reload
