---

################################################################################
#  description: Applies ChatOps PROD GLOBAL Updates on RHEL7x
#  usage: ansible-playbook ChatOps_PROD-GLOBAL_Apply-Updates-playbook.yml --extra-vars 'HostOrGroup=YourServerOrGroupNameGoesHere'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Apply ChatOps PROD GLOBAL Updates on RHEL7x
  hosts: "{{ HostOrGroup|default ('FATAL ERROR --> HostOrGroup NOT SET! You must specify either a Host or a Group name!') }}"
  serial: "100%"
  gather_facts: False
  tasks:


# Stop chatops.service
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Stop chatops-prod.service service
    service:
      name: chatops-prod.service
      enabled: yes
      state: stopped


# file - Sets attributes of files and folders
# REF: http://docs.ansible.com/ansible/file_module.html
##################################################################################

  - name: rm -rf /opt/chatops-prod.old if it exists!
    file:
      path: /opt/chatops-prod.old
      state: absent


# raw - Executes a low-down and dirty SSH command
# REF: http://docs.ansible.com/ansible/raw_module.html
######################################################

  - name: Rename the existing prod to create a fallback backup
    raw: if [ -d /opt/chatops-prod ]; then mv -f /opt/chatops-prod /opt/chatops-prod.old; fi


# file - Sets attributes of files and folders
# REF: http://docs.ansible.com/ansible/file_module.html
##################################################################################

# /opt/chatops-prod
  - name: Create directory /opt/chatops-prod
    file:
      path: /opt/chatops-prod
      state: directory
      mode: 0755
      owner: chatops
      group: wheel
      recurse: yes

# /opt/chatops-prod/scripts
  - name: Create directory /opt/chatops-prod/scripts
    file:
      path: /opt/chatops-prod/scripts
      state: directory
      mode: 0755
      owner: chatops
      group: wheel
      recurse: yes


# Use the copy module to copy various files into place
# REF: http://docs.ansible.com/ansible/copy_module.html
#######################################################

# /opt/chatops-prod/package.json
  - name: Copy files/ChatOps/Global/PROD/package.json to remote /opt/chatops-prod/package.json
    copy:
      src: files/ChatOps/Global/PROD/package.json
      dest: /opt/chatops-prod/package.json
      owner: chatops
      group: wheel
      mode: 0644

# /opt/chatops-prod/external-scripts.json
  - name: Copy files/ChatOps/Global/PROD/external-scripts.json to remote /opt/chatops-prod/external-scripts.json
    copy:
      src: files/ChatOps/Global/PROD/external-scripts.json
      dest: /opt/chatops-prod/external-scripts.json
      owner: chatops
      group: wheel
      mode: 0644


# Use npm to install and manage Node.js packages
# REF: http://docs.ansible.com/ansible/npm_module.html
######################################################

  - name: Run npm install in /opt/chatops-prod
    npm:
      path: /opt/chatops-prod
      state: latest
      production: yes
      global: no


# Update various configuration files
# REF: http://docs.ansible.com/ansible/lineinfile_module.html
#############################################################

  - name: Remove line from file /opt/chatops-prod/node_modules/hubot-auth/src/auth.coffee
    lineinfile:
      dest: /opt/chatops-prod/node_modules/hubot-auth/src/auth.coffee
      state: absent
      regexp: '^#   hubot (.*)'
      line: '#   hubot '


# Set attributes of files and folders
# REF: http://docs.ansible.com/ansible/file_module.html
#######################################################

  - name: Set directory permisions on PROD /opt/chatops-prod
    file:
      path: /opt/chatops-prod
      state: directory
      owner: chatops
      group: wheel
      recurse: yes


# raw - Executes a low-down and dirty SSH command
# REF: http://docs.ansible.com/ansible/raw_module.html
######################################################

  - name: systemctl daemon-reload
    shell: systemctl daemon-reload


# Enable and start chatops.service
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Enable and start the chatops-prod.service service
    service:
      name: chatops-prod.service
      enabled: yes
      state: restarted
      # Note: Verify PROD chatops-prod.service via SSH command line:
      # systemctl status chatops-prod.service    
