---

################################################################################
#  description: Applies ChatOps updates to PROD hubot-clc-satellites on RHEL7x
#  usage: ansible-playbook ChatOps_PROD-SATELLITE_Apply-hubot-clc-satellites-Updates-playbook.yml --extra-vars 'HostOrGroup=YourServerOrGroupNameGoesHere'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Apply ChatOps updates to PROD hubot-clc-satellites on RHEL7x
  hosts: "{{ HostOrGroup|default ('FATAL ERROR --> HostOrGroup NOT SET! You must specify either a Host or a Group name!') }}"
  serial: "100%"
  gather_facts: False
  tasks:


# Stop service
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Stop the PROD satellite-prod service
    service:
      name: satellite-prod.service
      state: stopped


# file - Sets attributes of files and folders
# REF: http://docs.ansible.com/ansible/file_module.html
##################################################################################

  - name: rm -rf /opt/satellite-prod.old if it exists!
    file:
      path: /opt/satellite-prod.old
      state: absent


# command - Executes a command on a remote node
# REF: http://docs.ansible.com/ansible/command_module.html
##########################################################


  - name: Rename the existing prod to create a fallback backup
    command: mv -f /opt/satellite-prod /opt/satellite-prod.old
 

# git - Deploy software (or files) from git checkouts
# REF: http://docs.ansible.com/ansible/git_module.html
######################################################

  - name: Update (git clone) hubot-clc-satellites to PROD /opt/satellite-prod
    git:
      repo: git@github.com:Tier3/hubot-clc-satellites.git
      version: master
      dest: /opt/satellite-prod
      accept_hostkey: yes
      key_file: /root/.ssh/chatops_cc-ansible_github_id_rsa
      update: yes


# Use npm to install and manage Node.js packages
# REF: http://docs.ansible.com/ansible/npm_module.html
######################################################

  - name: Run npm install in PROD /opt/satellite-prod
    npm:
      path: /opt/satellite-prod
      state: latest
      production: yes
      global: no


# Set attributes of files
# REF: http://docs.ansible.com/ansible/file_module.html
#######################################################

  - name: Set directory permisions on PROD /opt/satellite-prod
    file:
      path: /opt/satellite-prod
      state: directory
      owner: chatops
      group: wheel
      recurse: yes


# Enable and start the service
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Restart the PROD satellite-prod service
    service:
      name: satellite-prod.service
      state: restarted
      # Note: Verify PROD satellite via SSH command line:
      # systemctl status satellite-prod
