---

################################################################################
#  description: Uninstalls DEV Skynet on RHEL7x
#  usage: ansible-playbook ChatOps_DEV-Skynet_Uninstall-playbook.yml --extra-vars 'HostOrGroup=YourServerOrGroupNameGoesHere'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Uninstall DEV Skynet on RHEL7x
  hosts: "{{ HostOrGroup|default ('FATAL ERROR --> HostOrGroup NOT SET! You must specify either a Host or a Group name!') }}"
  serial: "100%"
  gather_facts: False
  tasks:


# service - Manage services
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Stop and disable the DEV Skynet-dev.service service
    service:
      name: skynet-dev.service
      enabled: no
      state: stopped


# file - Sets attributes of files and folders
# REF: http://docs.ansible.com/ansible/file_module.html
#######################################################

# /opt/skynet-dev
  - name: Delete DEV directory /opt/skynet-dev
    file:
      path: /opt/skynet-dev
      state: absent

# /etc/systemd/system/skynet-dev.service
  - name: Delete DEV file /etc/systemd/system/skynet-dev.service
    file:
      path: /etc/systemd/system/skynet-dev.service
      state: absent


# raw - Executes a low-down and dirty SSH command
# REF: http://docs.ansible.com/ansible/raw_module.html
######################################################

  - name: systemctl daemon-reload
    shell: systemctl daemon-reload
