---

################################################################################
#  description: Installs the ChatOps cc-ansible account GitHub RSA keys on RHEL7x
#  usage: ansible-playbook ChatOps_ALL_Install-RSA-keys-for-GitHub-access-playbook.yml --extra-vars 'HostOrGroup=ChatOpsSatellite'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Installs the ChatOps cc-ansible account GitHub RSA keys on RHEL7x
  hosts: "{{ HostOrGroup|default ('FATAL ERROR --> HostOrGroup NOT SET! You must specify either a Host or a Group name!') }}"
  serial: "100%"
  gather_facts: False
  tasks:


# Set attributes of files
# REF: http://docs.ansible.com/ansible/file_module.html
#######################################################

  - name: Create if missing and set directory permisions on /root/.ssh
    file:
      path: /root/.ssh
      state: directory
      owner: root
      group: root
      mode: 0700

# Use the copy module to copy various files into place
# REF: http://docs.ansible.com/ansible/copy_module.html
#######################################################

# /root/.ssh/chatops_cc-ansible_github_id_rsa
  - name: Copy PRIVATE RSA KEY files/rsa/chatops_cc-ansible_github_id_rsa to remote /root/.ssh/chatops_cc-ansible_github_id_rsa
    copy:
      src: files/rsa/chatops_cc-ansible_github_id_rsa
      dest: /root/.ssh/chatops_cc-ansible_github_id_rsa
      owner: root
      group: root
      mode: 0600

# /root/.ssh/chatops_cc-ansible_github_id_rsa.pub
  - name: Copy PUBLIC RSA KEY files/rsa/chatops_cc-ansible_github_id_rsa.pub to remote /root/.ssh/chatops_cc-ansible_github_id_rsa.pub
    copy:
      src: files/rsa/chatops_cc-ansible_github_id_rsa.pub
      dest: /root/.ssh/chatops_cc-ansible_github_id_rsa.pub
      owner: root
      group: root
      mode: 0644
