---

################################################################################
#  description: Installs pointer to our private Sinopia for NPM and add our Syslog logging on RHEL7x/CentOS7x
#  usage: ansible-playbook ChatOps_Kit_Configure-NPM-Registry-and-Logging-playbook.yml --extra-vars 'HostOrGroup=YourServerOrGroupNameGoesHere'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Install pointer to our private Sinopia for NPM and add our Syslog logging on RHEL7x/CentOS7x
  hosts: "{{ HostOrGroup|default ('FATAL ERROR --> HostOrGroup NOT SET! You must specify either a Host or a Group name!') }}"
  serial: "100%"
  gather_facts: False
  tasks:


# Update various configuration files
# REF: http://docs.ansible.com/ansible/lineinfile_module.html
#############################################################

  - name: Make sure required lines exist in /etc/rsyslog.conf (# ChatOps)
    lineinfile:
      dest: /etc/rsyslog.conf
      state: present
      regexp: '^# ChatOps (.*)'
      line: '# ChatOps'

  - name: Make sure required lines exist in /etc/rsyslog.conf (local0.info /var/log/chatops)
    lineinfile:
      dest: /etc/rsyslog.conf
      state: present
      regexp: '^local0.info                                             /var/log/chatops (.*)'
      line: 'local0.info                                             /var/log/chatops'

  - name: Make sure required lines exist in /etc/rsyslog.conf (local0.info @@10.125.194.201)
    lineinfile:
      dest: /etc/rsyslog.conf
      state: present
      regexp: '^local0.info     @@10.125.194.201 (.*)'
      line: 'local0.info     @@10.125.194.201'


# raw - Executes a low-down and dirty SSH command
# REF: http://docs.ansible.com/ansible/raw_module.html
######################################################

  - name: Set NPM Registry to our Private Sinopia Server
    raw: npm set registry "http://10.125.194.201:4873"


# Restart rsyslog
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Re-start the rsyslog service
    service:
      name: rsyslog
      enabled: yes
      state: restarted
      # Note: Verify rsyslog via SSH command line:
      # systemctl status rsyslog
