---

################################################################################
#  description: Installs ChatOps DEV GLOBAL kit on RHEL7x
#  usage: ansible-playbook ChatOps_DEV-GLOBAL_Install-playbook.yml --extra-vars 'HostOrGroup=YourServerOrGroupNameGoesHere HUBOT_SLACK_BOTNAME=YourHubotNameGoesHere HUBOT_SLACK_TOKEN=YourHubotSlackAPITokenKeyGoesHere HUBOT_AUTH_ADMIN=CommaSeperatedListofSlackIds CLC_V2_API_USERNAME=YourCenturyLinkCloudControlUsername CLC_V2_API_PASSWD=YourCenturyLinkCloudControlPassword HUBOT_GITHUB_USERNAME=YourAnsibleGitHubUsername HUBOT_GITHUB_PASSWORD=YourAnsibleGitHubPassword CHRYSUS_REDISPASS=RedisPasswordGoesHere ALICE_ZD_USERNAME=ZDUsernameGoesHere ALICE_ZD_PASSWORD=ZDPasswordGoesHere ZDV_USER=ZDVUsernameGoesHere ZDV_TOKEN=ZDVTokenGoesHere HUBOT_DS9_SA_USERNAME=DS9SaUsernameGoesHere HUBOT_DS9_SA_PASSWORD=DS9SaPasswordGoesHere'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Installs ChatOps DEV GLOBAL kit on RHEL7x
  hosts: "{{ HostOrGroup|default ('FATAL ERROR --> HostOrGroup NOT SET! You must specify either a Host or a Group name!') }}"
  serial: "100%"
  gather_facts: False
  tasks:


# Set attributes of files
# REF: http://docs.ansible.com/ansible/file_module.html
#######################################################

  - name: Create if missing and set directory permisions on /root/.ssh
    file:
      path: /root/.ssh
      state: directory
      owner: root
      group: root
      mode: 0700


# Use the copy module to copy various files into place
# REF: http://docs.ansible.com/ansible/copy_module.html
#######################################################

# /root/.ssh/chatops_cc-ansible_github_id_rsa
  - name: Copy PRIVATE RSA KEY files/rsa/chatops_cc-ansible_github_id_rsa to remote /root/.ssh/chatops_cc-ansible_github_id_rsa
    copy:
      src: files/rsa/chatops_cc-ansible_github_id_rsa
      dest: /root/.ssh/chatops_cc-ansible_github_id_rsa
      owner: root
      group: root
      mode: 0600


# /root/.ssh/chatops_cc-ansible_github_id_rsa.pub
  - name: Copy PUBLIC RSA KEY files/rsa/chatops_cc-ansible_github_id_rsa.pub to remote /root/.ssh/chatops_cc-ansible_github_id_rsa.pub
    copy:
      src: files/rsa/chatops_cc-ansible_github_id_rsa.pub
      dest: /root/.ssh/chatops_cc-ansible_github_id_rsa.pub
      owner: root
      group: root
      mode: 0644


# Create and manage user accounts
# REF: http://docs.ansible.com/ansible/user_module.html
#######################################################

  - name: Add user chatops to the OS so hubot does not run as root
    user:
      name: chatops
      comment: chatops
      group: wheel


# file - Sets attributes of files and folders
# REF: http://docs.ansible.com/ansible/file_module.html
##################################################################################

# /opt/chatops-dev
  - name: Create directory /opt/chatops-dev if it does not exist
    file:
      path: /opt/chatops-dev
      state: directory
      mode: 0755
      owner: chatops
      group: wheel
      recurse: yes

# /opt/chatops-dev/scripts
  - name: Create directory /opt/chatops-dev/scripts if it does not exist
    file:
      path: /opt/chatops-dev/scripts
      state: directory
      mode: 0755
      owner: chatops
      group: wheel
      recurse: yes


# Use the template module to populate files with data
# REF: http://docs.ansible.com/ansible/template_module.html
###########################################################

# /etc/systemd/system/chatops-dev.service
  - name: Fill in the variables and copy templates/ChatOps/Global/DEV/chatops-dev.service.j2 to remote /etc/systemd/system/chatops-dev.service
    template:
      src: templates/ChatOps/Global/DEV/chatops-dev.service.j2
      dest: /etc/systemd/system/chatops-dev.service
      owner: root
      group: wheel
      mode: 0644


# Use the copy module to copy various files into place
# REF: http://docs.ansible.com/ansible/copy_module.html
#######################################################

# /opt/chatops-dev/package.json
  - name: Copy files/ChatOps/Global/DEV/package.json to remote /opt/chatops-dev/package.json
    copy:
      src: files/ChatOps/Global/DEV/package.json
      dest: /opt/chatops-dev/package.json
      owner: chatops
      group: wheel
      mode: 0644

# /opt/chatops-dev/external-scripts.json
  - name: Copy files/ChatOps/Global/DEV/external-scripts.json to remote /opt/chatops-dev/external-scripts.json
    copy:
      src: files/ChatOps/Global/DEV/external-scripts.json
      dest: /opt/chatops-dev/external-scripts.json
      owner: chatops
      group: wheel
      mode: 0644


# Use npm to install and manage Node.js packages
# REF: http://docs.ansible.com/ansible/npm_module.html
######################################################

  - name: Run npm install in /opt/chatops-dev
    npm:
      path: /opt/chatops-dev
      state: latest
      production: yes
      global: no


# Update various configuration files
# REF: http://docs.ansible.com/ansible/lineinfile_module.html
#############################################################

  - name: Remove line from file /opt/chatops-dev/node_modules/hubot-auth/src/auth.coffee
    lineinfile:
      dest: /opt/chatops-dev/node_modules/hubot-auth/src/auth.coffee
      state: absent
      regexp: '^#   hubot (.*)'
      line: '#   hubot '


#################
# cc-hubot-help #
#################
#
# git - Deploy software (or files) from git checkouts
# REF: http://docs.ansible.com/ansible/git_module.html
######################################################

  - name: Git clone cc-hubot-help to DEV /opt/chatops-dev/node_modules/cc-hubot-help
    git:
      repo: git@github.com:CenturyLinkCloud/cc-hubot-help.git
      version: "{{cchubothelp|default ('master')}}"
      dest: /opt/chatops-dev/node_modules/cc-hubot-help
      accept_hostkey: yes
      key_file: /root/.ssh/chatops_cc-ansible_github_id_rsa

  - name: Run npm install in /opt/chatops-dev/node_modules/cc-hubot-help
    npm:
      path: /opt/chatops-dev/node_modules/cc-hubot-help
      state: latest
      production: yes
      global: no

########################
# cc-global-subscriber #
########################
#
# git - Deploy software (or files) from git checkouts
# REF: http://docs.ansible.com/ansible/git_module.html
######################################################

  - name: Git clone cc-global-subscriber to DEV /opt/chatops-dev/node_modules/cc-global-subscriber
    git:
      repo: git@github.com:CenturyLinkCloud/cc-global-subscriber.git
      version: "{{ccglobalsubscriber|default ('master')}}"
      dest: /opt/chatops-dev/node_modules/cc-global-subscriber
      accept_hostkey: yes
      key_file: /root/.ssh/chatops_cc-ansible_github_id_rsa

  - name: Run npm install in /opt/chatops-dev/node_modules/cc-global-subscriber
    npm:
      path: /opt/chatops-dev/node_modules/cc-global-subscriber
      state: latest
      production: yes
      global: no

##################
# cc-node-global #
##################
#
# git - Deploy software (or files) from git checkouts
# REF: http://docs.ansible.com/ansible/git_module.html
######################################################

  - name: Git clone cc-node-global to DEV /opt/chatops-dev/node_modules/cc-node-global
    git:
      repo: git@github.com:CenturyLinkCloud/cc-node-global.git
      version: "{{ccnodeglobal|default ('master')}}"
      dest: /opt/chatops-dev/node_modules/cc-node-global
      accept_hostkey: yes
      key_file: /root/.ssh/chatops_cc-ansible_github_id_rsa

  - name: Run npm install in /opt/chatops-dev/node_modules/cc-node-global
    npm:
      path: /opt/chatops-dev/node_modules/cc-node-global
      state: latest
      production: yes
      global: no

#################
# cc-node-pagerduty #
#################
#
# git - Deploy software (or files) from git checkouts
# REF: http://docs.ansible.com/ansible/git_module.html
######################################################

  - name: Git clone cc-node-pagerduty to DEV /opt/chatops-dev/node_modules/cc-node-pagerduty
    git:
      repo: git@github.com:CenturyLinkCloud/cc-node-pagerduty.git
      version: "{{ccnodepagerduty|default ('master')}}"
      dest: /opt/chatops-dev/node_modules/cc-node-pagerduty
      accept_hostkey: yes
      key_file: /root/.ssh/chatops_cc-ansible_github_id_rsa

  - name: Run npm install in /opt/chatops-dev/node_modules/cc-node-pagerduty
    npm:
      path: /opt/chatops-dev/node_modules/cc-node-pagerduty
      state: latest
      production: yes
      global: no

#################
# cc-node-slack #
#################
#
# git - Deploy software (or files) from git checkouts
# REF: http://docs.ansible.com/ansible/git_module.html
######################################################

  - name: Git clone cc-node-slack to DEV /opt/chatops-dev/node_modules/cc-node-slack
    git:
      repo: git@github.com:CenturyLinkCloud/cc-node-slack.git
      version: "{{ccnodeslack|default ('master')}}"
      dest: /opt/chatops-dev/node_modules/cc-node-slack
      accept_hostkey: yes
      key_file: /root/.ssh/chatops_cc-ansible_github_id_rsa

  - name: Run npm install in /opt/chatops-dev/node_modules/cc-node-slack
    npm:
      path: /opt/chatops-dev/node_modules/cc-node-slack
      state: latest
      production: yes
      global: no

##################
# cc-node-trello #
##################
#
# git - Deploy software (or files) from git checkouts
# REF: http://docs.ansible.com/ansible/git_module.html
######################################################

  - name: Git clone cc-node-trello to DEV /opt/chatops-dev/node_modules/cc-node-trello
    git:
      repo: git@github.com:CenturyLinkCloud/cc-node-trello.git
      version: "{{ccnodetrello|default ('master')}}"
      dest: /opt/chatops-dev/node_modules/cc-node-trello
      accept_hostkey: yes
      key_file: /root/.ssh/chatops_cc-ansible_github_id_rsa

  - name: Run npm install in /opt/chatops-dev/node_modules/cc-node-trello
    npm:
      path: /opt/chatops-dev/node_modules/cc-node-trello
      state: latest
      production: yes
      global: no

#####################
# hubot-clc-ansible #
#####################
#
# git - Deploy software (or files) from git checkouts
# REF: http://docs.ansible.com/ansible/git_module.html
######################################################
#
  - name: Git clone hubot-clc-ansible to DEV /opt/chatops-dev/node_modules/hubot-clc-ansible
    git:
      repo: git@github.com:Tier3/hubot-clc-ansible.git
      version: "{{hubotclcansible|default ('master')}}"
      dest: /opt/chatops-dev/node_modules/hubot-clc-ansible
      accept_hostkey: yes
      key_file: /root/.ssh/chatops_cc-ansible_github_id_rsa

  - name: Run npm install in /opt/chatops-dev/node_modules/hubot-clc-ansible
    npm:
      path: /opt/chatops-dev/node_modules/hubot-clc-ansible
      state: latest
      production: yes
      global: no

########################
# hubot-clc-dispatcher #
########################
#
# git - Deploy software (or files) from git checkouts
# REF: http://docs.ansible.com/ansible/git_module.html
######################################################
#
  - name: Git clone hubot-clc-dispatcher to DEV /opt/chatops-dev/node_modules/hubot-clc-dispatcher
    git:
      repo: git@github.com:Tier3/hubot-clc-dispatcher.git
      version: "{{hubotclcdispatcher|default ('master')}}"
      dest: /opt/chatops-dev/node_modules/hubot-clc-dispatcher
      accept_hostkey: yes
      key_file: /root/.ssh/chatops_cc-ansible_github_id_rsa

  - name: Run npm install in /opt/chatops-dev/node_modules/hubot-clc-dispatcher
    npm:
      path: /opt/chatops-dev/node_modules/hubot-clc-dispatcher
      state: latest
      production: yes
      global: no

#####################
# hubot-clc-zendesk #
#####################
#
# git - Deploy software (or files) from git checkouts
# REF: http://docs.ansible.com/ansible/git_module.html
######################################################

  - name: Git clone hubot-clc-zendesk to DEV /opt/chatops-dev/node_modules/hubot-clc-zendesk
    git:
      repo: git@github.com:Tier3/hubot-clc-zendesk.git
      version: "{{hubotclczendesk|default ('master')}}"
      dest: /opt/chatops-dev/node_modules/hubot-clc-zendesk
      accept_hostkey: yes
      key_file: /root/.ssh/chatops_cc-ansible_github_id_rsa

  - name: Run npm install in /opt/chatops-dev/node_modules/hubot-clc-zendesk
    npm:
      path: /opt/chatops-dev/node_modules/hubot-clc-zendesk
      state: latest
      production: yes
      global: no

####################
# hubot-clc-zenoss #
####################
#
# git - Deploy software (or files) from git checkouts
# REF: http://docs.ansible.com/ansible/git_module.html
######################################################
#
  - name: Git clone hubot-clc-zenoss to DEV /opt/chatops-dev/node_modules/hubot-clc-zenoss
    git:
      repo: git@github.com:Tier3/hubot-clc-zenoss.git
      version: "{{hubotclczenoss|default ('master')}}"
      dest: /opt/chatops-dev/node_modules/hubot-clc-zenoss
      accept_hostkey: yes
      key_file: /root/.ssh/chatops_cc-ansible_github_id_rsa

  - name: Run npm install in /opt/chatops-dev/node_modules/hubot-clc-zenoss
    npm:
      path: /opt/chatops-dev/node_modules/hubot-clc-zenoss
      state: latest
      production: yes
      global: no

####################
# node-clc-zenoss #
####################
#
# git - Deploy software (or files) from git checkouts
# REF: http://docs.ansible.com/ansible/git_module.html
######################################################
#
  - name: Git clone node-clc-zenoss to DEV /opt/chatops-dev/node_modules/node-clc-zenoss
    git:
      repo: git@github.com:Tier3/node-clc-zenoss.git
      version: "{{nodeclczenoss|default ('master')}}"
      dest: /opt/chatops-dev/node_modules/node-clc-zenoss
      accept_hostkey: yes
      key_file: /root/.ssh/chatops_cc-ansible_github_id_rsa

  - name: Run npm install in /opt/chatops-dev/node_modules/node-clc-zenoss
    npm:
      path: /opt/chatops-dev/node_modules/node-clc-zenoss
      state: latest
      production: yes
      global: no

####################
# cc-hubot-forecast #
####################
#
# git - Deploy software (or files) from git checkouts
# REF: http://docs.ansible.com/ansible/git_module.html
######################################################
#
  - name: Git clone cc-hubot-forecast to DEV /opt/chatops-dev/node_modules/cc-hubot-forecast
    git:
      repo: git@github.com:CenturyLinkCloud/cc-hubot-forecast.git
      version: "{{cchubotforecast|default ('master')}}"
      dest: /opt/chatops-dev/node_modules/cc-hubot-forecast
      accept_hostkey: yes
      key_file: /root/.ssh/chatops_cc-ansible_github_id_rsa

  - name: Run npm install in /opt/chatops-dev/node_modules/cc-hubot-forecast
    npm:
      path: /opt/chatops-dev/node_modules/cc-hubot-forecast
      state: latest
      production: yes
      global: no

# Set attributes of files and folders
# REF: http://docs.ansible.com/ansible/file_module.html
#######################################################

# /opt/chatops-dev/chatops.service
  - name: Create a symbolic link - ln -s /etc/systemd/system/chatops-dev.service /opt/chatops-dev/chatops.service
    file:
      src: /etc/systemd/system/chatops-dev.service
      dest: /opt/chatops-dev/chatops.service
      state: link
      owner: root
      group: wheel

  - name: Set directory permisions on DEV /opt/chatops-dev
    file:
      path: /opt/chatops-dev
      state: directory
      owner: chatops
      group: wheel
      recurse: yes


# Use the copy module to copy various files into place
# REF: http://docs.ansible.com/ansible/copy_module.html
#######################################################

  - name: Copy the data loader script files/Redis/import_dcInfo.js to remote /tmp/import_dcInfo.js
    copy:
      src: files/Redis/import_dcInfo.js
      dest: /tmp/import_dcInfo.js
      owner: root
      group: root
      mode: 0600


# raw - Executes a low-down and dirty SSH command
# REF: http://docs.ansible.com/ansible/raw_module.html
######################################################

  - name: cd /tmp && npm install redis
    shell: cd /tmp && npm install redis

  - name: cd /tmp && node import_dcInfo.js
    shell: cd /tmp && node import_dcInfo.js


# Set attributes of files and folders
# REF: http://docs.ansible.com/ansible/file_module.html
#######################################################

  - name: Delete temporary file /tmp/import_dcInfo.js
    file:
      path: /tmp/import_dcInfo.js
      state: absent

  - name: Delete temporary directory /tmp/node_modules
    file:
      path: /tmp/node_modules
      state: absent


# raw - Executes a low-down and dirty SSH command
# REF: http://docs.ansible.com/ansible/raw_module.html
######################################################

  - name: systemctl daemon-reload
    shell: systemctl daemon-reload


# Enable and start chatops-dev.service
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Enable and start the chatops-dev.service service
    service:
      name: chatops-dev.service
      enabled: yes
      state: restarted
      # Note: Verify DEV chatops-dev.service via SSH command line:
      # systemctl status chatops-dev.service    
