---

################################################################################
#  description: Updates Redis data for ChatOps PROD GLOBAL kit on RHEL7x
#  usage: ansible-playbook ChatOps_PROD-GLOBAL_Update-Redis-Data-playbook.yml --extra-vars 'HostOrGroup=YourServerOrGroupNameGoesHere'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Update Redis data for ChatOps PROD GLOBAL kit on RHEL7x
  hosts: "{{ HostOrGroup|default ('FATAL ERROR --> HostOrGroup NOT SET! You must specify either a Host or a Group name!') }}"
  serial: "100%"
  gather_facts: False
  tasks:


# Use the copy module to copy various files into place
# REF: http://docs.ansible.com/ansible/copy_module.html
#######################################################

  - name: Copy the data loader script files/Redis/import_dcInfo.js to remote /tmp/import_dcInfo.js
    copy:
      src: files/Redis/import_dcInfo.js
      dest: /tmp/import_dcInfo.js
      owner: root
      group: root
      mode: 0600


# raw - Executes a low-down and dirty SSH command
# REF: http://docs.ansible.com/ansible/raw_module.html
######################################################

  - name: cd /tmp && npm install redis
    shell: cd /tmp && npm install redis

  - name: cd /tmp && node import_dcInfo.js
    shell: cd /tmp && node import_dcInfo.js


# Set attributes of files and folders
# REF: http://docs.ansible.com/ansible/file_module.html
#######################################################

  - name: Delete temporary file /tmp/import_dcInfo.js
    file:
      path: /tmp/import_dcInfo.js
      state: absent

  - name: Delete temporary directory /tmp/node_modules
    file:
      path: /tmp/node_modules
      state: absent
