---

################################################################################
#  description: Installs ChatOps PROD GLOBAL kit on RHEL7x
#  usage: ansible-playbook ChatOps_PROD-GLOBAL_Install-playbook.yml --extra-vars 'HostOrGroup=YourServerOrGroupNameGoesHere HUBOT_SLACK_BOTNAME=YourHubotNameGoesHere HUBOT_SLACK_TOKEN=YourHubotSlackAPITokenKeyGoesHere HUBOT_AUTH_ADMIN=CommaSeperatedListofSlackIds CLC_V2_API_USERNAME=YourCenturyLinkCloudControlUsername CLC_V2_API_PASSWD=YourCenturyLinkCloudControlPassword HUBOT_GITHUB_USERNAME=YourAnsibleGitHubUsername HUBOT_GITHUB_PASSWORD=YourAnsibleGitHubPassword CHRYSUS_REDISPASS=RedisPasswordGoesHere ALICE_ZD_USERNAME=ZDUsernameGoesHere ALICE_ZD_PASSWORD=ZDPasswordGoesHere ZDV_USER=ZDVUsernameGoesHere ZDV_TOKEN=ZDVTokenGoesHere HUBOT_DS9_SA_USERNAME=DS9SaUsernameGoesHere HUBOT_DS9_SA_PASSWORD=DS9SaPasswordGoesHere'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Install ChatOps PROD GLOBAL kit on RHEL7x
  hosts: "{{ HostOrGroup|default ('FATAL ERROR --> HostOrGroup NOT SET! You must specify either a Host or a Group name!') }}"
  serial: "100%"
  gather_facts: False
  tasks:


# Set attributes of files
# REF: http://docs.ansible.com/ansible/file_module.html
#######################################################

  - name: Create if missing and set directory permisions on /root/.ssh
    file:
      path: /root/.ssh
      state: directory
      owner: root
      group: root
      mode: 0700


# Use the copy module to copy various files into place
# REF: http://docs.ansible.com/ansible/copy_module.html
#######################################################

# /root/.ssh/chatops_cc-ansible_github_id_rsa
  - name: Copy PRIVATE RSA KEY files/rsa/chatops_cc-ansible_github_id_rsa to remote /root/.ssh/chatops_cc-ansible_github_id_rsa
    copy:
      src: files/rsa/chatops_cc-ansible_github_id_rsa
      dest: /root/.ssh/chatops_cc-ansible_github_id_rsa
      owner: root
      group: root
      mode: 0600


# /root/.ssh/chatops_cc-ansible_github_id_rsa.pub
  - name: Copy PUBLIC RSA KEY files/rsa/chatops_cc-ansible_github_id_rsa.pub to remote /root/.ssh/chatops_cc-ansible_github_id_rsa.pub
    copy:
      src: files/rsa/chatops_cc-ansible_github_id_rsa.pub
      dest: /root/.ssh/chatops_cc-ansible_github_id_rsa.pub
      owner: root
      group: root
      mode: 0644


# Create and manage user accounts
# REF: http://docs.ansible.com/ansible/user_module.html
#######################################################

  - name: Add user chatops to the OS so hubot does not run as root
    user:
      name: chatops
      comment: chatops
      group: wheel


# file - Sets attributes of files and folders
# REF: http://docs.ansible.com/ansible/file_module.html
##################################################################################

# /opt/chatops-prod
  - name: Create directory /opt/chatops-prod if it does not exist
    file:
      path: /opt/chatops-prod
      state: directory
      mode: 0755
      owner: chatops
      group: wheel
      recurse: yes

# /opt/chatops-prod/scripts
  - name: Create directory /opt/chatops-prod/scripts if it does not exist
    file:
      path: /opt/chatops-prod/scripts
      state: directory
      mode: 0755
      owner: chatops
      group: wheel
      recurse: yes


# Use the template module to populate files with data
# REF: http://docs.ansible.com/ansible/template_module.html
###########################################################

# /etc/systemd/system/chatops-prod.service
  - name: Fill in the variables and copy templates/ChatOps/Global/PROD/chatops-prod.service.j2 to remote /etc/systemd/system/chatops-prod.service
    template:
      src: templates/ChatOps/Global/PROD/chatops-prod.service.j2
      dest: /etc/systemd/system/chatops-prod.service
      owner: root
      group: wheel
      mode: 0644


# Use the copy module to copy various files into place
# REF: http://docs.ansible.com/ansible/copy_module.html
#######################################################

# /opt/chatops-prod/package.json
  - name: Copy files/ChatOps/Global/PROD/package.json to remote /opt/chatops-prod/package.json
    copy:
      src: files/ChatOps/Global/PROD/package.json
      dest: /opt/chatops-prod/package.json
      owner: chatops
      group: wheel
      mode: 0644

# /opt/chatops-prod/external-scripts.json
  - name: Copy files/ChatOps/Global/PROD/external-scripts.json to remote /opt/chatops-prod/external-scripts.json
    copy:
      src: files/ChatOps/Global/PROD/external-scripts.json
      dest: /opt/chatops-prod/external-scripts.json
      owner: chatops
      group: wheel
      mode: 0644


# Use npm to install and manage Node.js packages
# REF: http://docs.ansible.com/ansible/npm_module.html
######################################################

  - name: Run npm install in /opt/chatops-prod
    npm:
      path: /opt/chatops-prod
      state: latest
      production: yes
      global: no


# Update various configuration files
# REF: http://docs.ansible.com/ansible/lineinfile_module.html
#############################################################

  - name: Remove line from file /opt/chatops-prod/node_modules/hubot-auth/src/auth.coffee
    lineinfile:
      dest: /opt/chatops-prod/node_modules/hubot-auth/src/auth.coffee
      state: absent
      regexp: '^#   hubot (.*)'
      line: '#   hubot '


# Set attributes of files and folders
# REF: http://docs.ansible.com/ansible/file_module.html
#######################################################

# /opt/chatops-prod/chatops.service
  - name: Create a symbolic link - ln -s /etc/systemd/system/chatops-prod.service /opt/chatops-prod/chatops.service
    file:
      src: /etc/systemd/system/chatops-prod.service
      dest: /opt/chatops-prod/chatops.service
      state: link
      owner: root
      group: wheel

  - name: Set directory permisions on PROD /opt/chatops-prod
    file:
      path: /opt/chatops-prod
      state: directory
      owner: chatops
      group: wheel
      recurse: yes


# Use the copy module to copy various files into place
# REF: http://docs.ansible.com/ansible/copy_module.html
#######################################################

  - name: Copy the data loader script files/Redis/import_dcInfo.js to remote /tmp/import_dcInfo.js
    copy:
      src: files/Redis/import_dcInfo.js
      dest: /tmp/import_dcInfo.js
      owner: root
      group: root
      mode: 0600


# raw - Executes a low-down and dirty SSH command
# REF: http://docs.ansible.com/ansible/raw_module.html
######################################################

  - name: cd /tmp && npm install redis
    shell: cd /tmp && npm install redis

  - name: cd /tmp && node import_dcInfo.js
    shell: cd /tmp && node import_dcInfo.js


# Set attributes of files and folders
# REF: http://docs.ansible.com/ansible/file_module.html
#######################################################

  - name: Delete temporary file /tmp/import_dcInfo.js
    file:
      path: /tmp/import_dcInfo.js
      state: absent

  - name: Delete temporary directory /tmp/node_modules
    file:
      path: /tmp/node_modules
      state: absent


# raw - Executes a low-down and dirty SSH command
# REF: http://docs.ansible.com/ansible/raw_module.html
######################################################

  - name: systemctl daemon-reload
    shell: systemctl daemon-reload


# Enable and start chatops.service
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Enable and start the chatops-prod.service
    service:
      name: chatops-prod.service
      enabled: yes
      state: restarted
      # Note: Verify PROD chatops-prod.service via SSH command line:
      # systemctl status chatops-prod.service    
