---

- name: Set Customer Care standard WSManCredSSP settings
  hosts: "{{ defaultcustomercarenocboxgroup }}"
  vars_files:
    - host_vars/default.yml
  gather_facts: False
  tasks:
  - name: Run the PowerShell script on each server
    script: files/WSManCredSSP/ConfigureWSManCredSSP.ps1 
