---

# Run the join domain script in files/JoinT3NDomain/joinT3N.ps1 on "{{ defaultcustomercarenocboxgroup }}" 
- name: Have the server join the T3N domain if not already part of it
  hosts: "{{ defaultcustomercarenocboxgroup }}" 
  vars_files:
    - host_vars/default.yml
  gather_facts: False
  tasks:
    - name: Run the PowerShell script on each server
      script: files/JoinT3NDomain/joinT3N.ps1 

# Reboot
- name: Reboot "{{ defaultcustomercarenocboxgroup }}"
  hosts: "{{ defaultcustomercarenocboxgroup }}"
  vars_files:
    - host_vars/default.yml
  gather_facts: false
  ignore_errors: yes
  force_handlers: True
  roles:
    - role: trondhindenes.win_reboot
  vars:
    winreboot_simulate: yes
    winreboot_cooldown_period: 10
    winreboot_winrm_delay: 60
    winreboot_winrm_retries: 2

