---

################################################################################
#  description: Add second Redis instance on RHEL7x
#  usage: ansible-playbook RHEL7_ChatOps_Redis_Instance.yml --extra-vars 'HostOrGroup=YourServerOrGroupNameGoesHere CHATOPS_REDIS_IP=YourIpGoesHere CHATOPS_REDIS_PORT=YourPortGoesHere CHATOPS_REDIS_INSTANCE=YourInstanceNameGoesHere'
#  author: Kevin Martin <21.kmart@gmail.com> (https://github.com/kmart2234)
#  license: MIT
################################################################################

# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Add second Redis instance on RHEL7x
  hosts: "{{ HostOrGroup|default ('FATAL ERROR --> HostOrGroup NOT SET! You must specify either a Host or a Group name!') }}"
  serial: "100%"
  gather_facts: False
  tasks:

# Create and manage user accounts
# REF: http://docs.ansible.com/ansible/user_module.html
#######################################################

  - name: Add user redis to the OS so ChatOps Redis does not run as root
    user:
      name: redis
      comment: redis
      group: wheel


# file - Sets attributes of files and folders
# REF: http://docs.ansible.com/ansible/file_module.html
##################################################################################

# /var/lib/CHATOPS_REDIS_INSTANCE-redis
  - name: Create redis directory if it does not exist /var/lib/{{ CHATOPS_REDIS_INSTANCE }}-redis
    file:
      path: "/var/lib/{{ CHATOPS_REDIS_INSTANCE }}-redis"
      state: directory
      mode: 0755
      owner: redis
      group: wheel
      recurse: yes


# Use the template module to populate files with data
# REF: http://docs.ansible.com/ansible/template_module.html
###########################################################

# /etc/{{ CHATOPS_REDIS_INSTANCE}}-redis.conf
  - name: Fill in the variables and copy templates/chatops-redis.conf.j2 to remote /etc/{{ CHATOPS_REDIS_INSTANCE}}-redis.conf
    template:
      src: templates/Redis/chatops-redis.conf.j2
      dest: "/etc/{{ CHATOPS_REDIS_INSTANCE }}-redis.conf"
      owner: root
      group: wheel
      mode: 0644


# Use the copy module to copy various files into place
# REF: http://docs.ansible.com/ansible/copy_module.html
#######################################################

# /usr/lib/systemd/system/YourInstanceNameGoesHere-redis.service
  - name: Copy files/ChatOps-Redis/chatops-redis.service to remote /usr/lib/systemd/system/{{ CHATOPS_REDIS_INSTANCE}}-redis.service
    template:
      src: templates/Redis/chatops-redis.service.j2
      dest: "/usr/lib/systemd/system/{{ CHATOPS_REDIS_INSTANCE }}-redis.service"
      owner: root
      group: wheel
      mode: 0644


# raw - Executes a low-down and dirty SSH command
# REF: http://docs.ansible.com/ansible/raw_module.html
######################################################

  - name: systemctl daemon-reload
    shell: systemctl daemon-reload


# Enable and start chatops-redis.service
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Enable and start the {{ CHATOPS_REDIS_INSTANCE}}-redis.service
    service:
      name: "{{ CHATOPS_REDIS_INSTANCE }}-redis.service"
      enabled: yes
      state: restarted
      # Note: Verify PROD YourInstance-redis.service via SSH command line:
      # systemctl status YourInstance-redis.service